/**
 * Compiles seed/traversata.json into sql/traversata_seed.sql — one INSERT OR IGNORE per
 * mode, each with a freshly minted 24-hex share token. OR IGNORE means an applied row
 * keeps its ORIGINAL token forever (re-runs never rotate a link someone already holds);
 * rotation is deliberate, via POST /api/journal/traversata/:key/rotate. The generated
 * file carries live tokens and is gitignored.
 *
 * Run: node --experimental-strip-types scripts/traversata-seed-build.ts
 * Apply: npm run db:seed:traversata
 */
import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(HERE, '..', 'seed/traversata.json');
const OUT = path.resolve(HERE, '..', 'sql/traversata_seed.sql');

const q = (s: string): string => `'${s.replace(/'/g, "''")}'`;

interface Mode { key: string; label: string; star: string; dedication: string; summary: string; long: string; glossary: { term: string; def: string }[]; programme: string; intimate?: boolean }

const { modes } = JSON.parse(readFileSync(SRC, 'utf8')) as { modes: Mode[] };
const stmts = modes.map((m) => {
  if (!/^[a-z]{2,16}$/.test(m.key)) throw new Error(`bad mode key: ${m.key}`);
  const token = randomBytes(12).toString('hex');
  const { key: _k, ...doc } = m;
  return `INSERT OR IGNORE INTO traversata_modes (key, token, json) VALUES (${q(m.key)}, ${q(token)}, ${q(JSON.stringify(doc))});`;
});

writeFileSync(OUT, `-- generated by scripts/traversata-seed-build.ts — tokens inside, keep out of git\n${stmts.join('\n')}\n`);
console.log(`wrote ${OUT}: ${modes.length} modes (${modes.map((m) => m.key).join(', ')})`);
